[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "trakky"
dynamic = ["version"]

[project.optional-dependencies]
dev = ['pytest']

[project.scripts]
trakky = "trakky:main.cli"
